#!/bin/sh
java -classpath /mnt/c/Users/housi/Desktop/Stanford-Compilers/CS143/lib:.:/mnt/c/Users/housi/Desktop/Stanford-Compilers/CS143/Stanford-CS143-Compilers/semantic-analysis/classes/:`dirname $0` Semant $*
