#!/bin/sh
java -classpath /mnt/c/Users/housi/Desktop/Stanford-Compilers/assets/lib/java-cup-11a.jar:/mnt/c/Users/housi/Desktop/Stanford-Compilers/assets/lib/jlex.jar:/mnt/c/Users/housi/Desktop/Stanford-Compilers/assets/assignments/PA2J:/usr/java/lib/rt.jar:/mnt/c/Users/housi/Desktop/Stanford-Compilers/assets/assignments/PA2J/classes:`dirname $0` Lexer $*
